/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/auth/sign-in': RouteRecordInfo<'/auth/sign-in', '/auth/sign-in', Record<never, never>, Record<never, never>>,
    '/auth/sign-up/': RouteRecordInfo<'/auth/sign-up/', '/auth/sign-up', Record<never, never>, Record<never, never>>,
    '/auth/sign-up/confirm': RouteRecordInfo<'/auth/sign-up/confirm', '/auth/sign-up/confirm', Record<never, never>, Record<never, never>>,
    '/auth/sign-up/workspace': RouteRecordInfo<'/auth/sign-up/workspace', '/auth/sign-up/workspace', Record<never, never>, Record<never, never>>,
    '/boards/': RouteRecordInfo<'/boards/', '/boards', Record<never, never>, Record<never, never>>,
    '/boards/[id]': RouteRecordInfo<'/boards/[id]', '/boards/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/members': RouteRecordInfo<'/members', '/members', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/tasks': RouteRecordInfo<'/tasks', '/tasks', Record<never, never>, Record<never, never>>,
    '/templates': RouteRecordInfo<'/templates', '/templates', Record<never, never>, Record<never, never>>,
  }
}
