// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@3.17.3_@parcel+watcher@2.5.1_@types+node@22.10.1_db0@0.3.2_eslint@9.14.0_jiti@2.4.2__ior_bme2vjdkfzmbrrp5vfpm26yuc4/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+compiler-dom@3.5.13_eslint@9.14.0_jiti@2.4.2__magicast@0.3.5_rollup@4_7sls34rd762jy7uy4pn2pcohdy/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+compiler-dom@3.5.13_eslint@9.14.0_jiti@2.4.2__magicast@0.3.5_rollup@4_7sls34rd762jy7uy4pn2pcohdy/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+compiler-dom@3.5.13_eslint@9.14.0_jiti@2.4.2__magicast@0.3.5_rollup@4_7sls34rd762jy7uy4pn2pcohdy/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@una-ui+nuxt@0.54.3_@unocss+preset-wind3@66.1.1_@unocss+webpack@66.1.1_webpack@5.99.8_esbuild_zjy45c37pnckxxqdrw4qp24zu4/node_modules/@una-ui/nuxt/dist/runtime/plugins/theme.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@una-ui+nuxt@0.54.3_@unocss+preset-wind3@66.1.1_@unocss+webpack@66.1.1_webpack@5.99.8_esbuild_zjy45c37pnckxxqdrw4qp24zu4/node_modules/@una-ui/nuxt/dist/runtime/plugins/theme.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+icon@1.12.0_magicast@0.3.5_vite@6.3.5_@types+node@22.10.1_jiti@2.4.2_lightningcss@1.29._d47wwnxiig5hzp5tpdhy2vhjia/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@9.5.4_@vue+compiler-dom@3.5.13_eslint@9.14.0_jiti@2.4.2__magicast@0.3.5_rollup@4_7sls34rd762jy7uy4pn2pcohdy/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin' | 'nuxt:global-components' | '@nuxt/icon' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
