name: Go CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service]
    defaults:
      run:
        working-directory: ./apps/${{ matrix.service }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: apps/server/${{ matrix.service }}/go.mod

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test -race -v ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service]
    defaults:
      run:
        working-directory: ./apps/server/${{ matrix.service }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: apps/${{ matrix.service }}/go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: apps/${{ matrix.service }}
