name: Github to Telegram Notifier

on:
  fork:
  push:
  release:
    types: published
  issue_comment:
    types: created
  watch:
    types: started
  pull_request_review_comment:
    types: created
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, pinned, closed, reopened]

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on push
        if: ${{ github.event_name == 'push' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            📢 ${{ github.actor }} pushed a commit:
            - Message: ${{ github.event.commits[0].message }}
            - Repository: ${{ github.repository }}
            🔗 [View Changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

      - name: Notify on pull request
        if: ${{ github.event_name == 'pull_request' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🔄 ${{ github.actor }} create pull request
            - Action: ${{ github.event.action }}
            - Title: ${{ github.event.pull_request.title }}
            - PR URL: ${{ github.event.pull_request.html_url }}
            Repository: ${{ github.repository }}

      - name: Notify on issue
        if: ${{ github.event_name == 'issues' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            📝 ${{ github.actor }} create issue
            - Action: ${{ github.event.action }}
            - Title: ${{ github.event.issue.title }}
            - URL: ${{ github.event.issue.html_url }}
            Repository: ${{ github.repository }}
