name: Github to Telegram Notifier

on:
  fork:
  push:
  release:
    types: published
  issue_comment:
    types: created
  watch:
    types: started
  pull_request_review_comment:
    types: created
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, pinned, closed, reopened]

jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: push notification
        uses: EverythingSuckz/github-telegram-notify@main
        continue-on-error: true
        with:
          bot_token: '${{ secrets.BOT_TOKEN }}'
          chat_id: '${{ secrets.CHAT_ID }}'
