name: Create issues from TODOs

on:
  push:
    branches: 
      - dev

permissions:
  issues: write
  repository-projects: read
  contents: read

jobs:
  todos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Bot
        uses: derjuulsn/todo-issue@main
        with:
          excludePattern: '^(node_modules/|.vscode/)'
          autoAssign: 'true'
          keywords: 'TODO'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}